const projectStates = [
  "plan_saved",
  "plan_sent",
  "plan_review_teacher",
  "plan_corrections_done",
  "plan_approved_director",
  "san_curriculum_1",
  "plan_review_commission",
  "plan_corrections_done2",
  "plan_approved_commission",
  "plan_rejected",
  "project_uploaded",
  "project_review_teacher",
  "project_corrections_done",
  "project_approved_director",
  "san_curriculum_2",
  "tribunal_assigned",
  "project_graded",
  "project_corrections_done_2",
  "project_approved_send",
  "test_defense_apt",
  "date_defense_assigned",
  "project_rejected",
  "project_completed",
];

export default projectStates;
